import { Inter } from 'next/font/google'
import { Mooli } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const mooli = Mooli({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Artistas ',
  description: 'Generated by cristian',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={mooli.className}>

        <div className='flex flex-col min-h-screen'>
          <Navbar/>

          <main className='flex-grow '>
              {children}
              <Footer/>
          </main>

        </div>

      </body>
    </html>
  )
}
